# Generated by Django 4.0.5 on 2022-07-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('stock', models.CharField(max_length=10)),
                ('precio', models.CharField(max_length=30)),
            ],
        ),
    ]
