# Generated by Django 4.0.5 on 2022-07-06 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion2App', '0002_producto_delete_productos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='producto',
            new_name='productos',
        ),
    ]
