# Generated by Django 4.0.5 on 2022-07-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluacion2App', '0003_rename_producto_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='productos',
        ),
    ]
